"""Core solver-independent domain models."""

from wre.domain.adapter_capabilities import AdapterCapabilityDescriptor, AdapterCapabilityName
from wre.domain.artifact_graph import ArtifactDependencyEdge, ArtifactDependencyGraph
from wre.domain.artifact_invalidation import (
    ArtifactInvalidationPlan,
    plan_artifact_invalidation,
)
from wre.domain.artifact_keys import (
    ARTIFACT_KEY_SCHEMA_VERSION,
    ArtifactInputFingerprint,
    ArtifactKey,
    ArtifactKeyMaterial,
    canonical_artifact_key_bytes,
    derive_artifact_key,
)
from wre.domain.artifact_materialization import (
    ArtifactMaterializationEntry,
    ArtifactMaterializationMetadata,
    ArtifactMaterializationVerification,
    ArtifactMaterializationVerificationStatus,
)
from wre.domain.artifact_metadata import ArtifactMetadata
from wre.domain.artifacts import ArtifactId, ArtifactKind, ArtifactRef
from wre.domain.benchmarks import (
    BenchmarkFixtureId,
    BenchmarkFixtureIdentity,
    BenchmarkRecord,
    BenchmarkRecordId,
)
from wre.domain.cameras import (
    Camera,
    CameraId,
    ImageDimensions,
    ObservationMetadata,
    RawMetadataEntry,
)
from wre.domain.decoded_images import (
    DECODED_IMAGE_PYRAMID_KIND,
    DecodedImageLevelDescriptor,
    DecodedImageOrientationPolicy,
    DecodedImagePixelLayout,
    DecodedImagePyramidManifest,
    DecodedImagePyramidSpec,
    build_decoded_image_level_descriptors,
)
from wre.domain.estimated_geometry import (
    CameraCalibrationEstimate,
    CameraCalibrationEstimateId,
    CameraPoseEstimate,
    EstimatedPoint3DId,
    EstimatedTrackElement,
    LocalScaleStatus,
    Point3DEstimate,
    SparseReconstructionEstimate,
    SparseReconstructionEstimateId,
)
from wre.domain.failures import FailureCategory
from wre.domain.fragments import LocalFrameId, SpatialFragment, SpatialFragmentId
from wre.domain.frame_selection import (
    FrameSelectionPolicy,
    FrameSelectionPolicyId,
    FrameSelectionPolicyRevision,
)
from wre.domain.hardware_identity import HardwareRuntimeIdentity
from wre.domain.media_profiles import MediaProfile
from wre.domain.metadata import (
    CaptureTimeInterpretation,
    CaptureTimeInterpretationStatus,
    GpsInterpretationStatus,
    GpsMetadataInterpretation,
    ObservationMetadataInterpretation,
)
from wre.domain.metrics import (
    MetricAggregation,
    MetricDescriptor,
    MetricDimension,
    MetricDirection,
    MetricName,
    MetricObservation,
    MetricProvenance,
    MetricUnit,
    MetricVector,
)
from wre.domain.observations import (
    ImageObservation,
    MediaAssetRef,
    Observation,
    ObservationId,
    ObservationKind,
    Sha256Digest,
    SourceId,
    SourceRef,
    VideoFrameObservation,
    VideoObservation,
)
from wre.domain.producer_identity import (
    ArtifactProducerIdentity,
    CheckpointIdentity,
    ConfigurationIdentity,
    ModelIdentity,
)
from wre.domain.projects import SceneProject, SceneProjectId
from wre.domain.provenance import ProvenanceClass
from wre.domain.quality import QualityDecision, QualityMode
from wre.domain.quality_policy import (
    QualityEvaluation,
    QualityEvaluationReason,
    QualityEvaluationReasonKind,
    QualityPolicy,
    QualityPolicyFailureRule,
    QualityPolicyId,
    QualityPolicyMetricRule,
    QualityPolicyRevision,
    evaluate_quality_policy,
)
from wre.domain.runs import (
    DerivedArtifactProvenance,
    ProducerRef,
    ReconstructionRun,
    ReconstructionRunId,
)

__all__ = [
    "ARTIFACT_KEY_SCHEMA_VERSION",
    "AdapterCapabilityDescriptor",
    "AdapterCapabilityName",
    "ArtifactDependencyEdge",
    "ArtifactDependencyGraph",
    "ArtifactId",
    "ArtifactInputFingerprint",
    "ArtifactInvalidationPlan",
    "ArtifactKey",
    "ArtifactKeyMaterial",
    "ArtifactKind",
    "ArtifactMaterializationEntry",
    "ArtifactMaterializationMetadata",
    "ArtifactMaterializationVerification",
    "ArtifactMaterializationVerificationStatus",
    "ArtifactMetadata",
    "ArtifactProducerIdentity",
    "ArtifactRef",
    "BenchmarkFixtureId",
    "BenchmarkFixtureIdentity",
    "BenchmarkRecord",
    "BenchmarkRecordId",
    "Camera",
    "CameraCalibrationEstimate",
    "CameraCalibrationEstimateId",
    "CameraId",
    "CameraPoseEstimate",
    "CaptureTimeInterpretation",
    "CaptureTimeInterpretationStatus",
    "CheckpointIdentity",
    "ConfigurationIdentity",
    "DECODED_IMAGE_PYRAMID_KIND",
    "DecodedImageLevelDescriptor",
    "DecodedImageOrientationPolicy",
    "DecodedImagePixelLayout",
    "DecodedImagePyramidManifest",
    "DecodedImagePyramidSpec",
    "DerivedArtifactProvenance",
    "EstimatedPoint3DId",
    "EstimatedTrackElement",
    "FailureCategory",
    "FrameSelectionPolicy",
    "FrameSelectionPolicyId",
    "FrameSelectionPolicyRevision",
    "GpsInterpretationStatus",
    "GpsMetadataInterpretation",
    "HardwareRuntimeIdentity",
    "ImageDimensions",
    "ImageObservation",
    "LocalFrameId",
    "LocalScaleStatus",
    "MediaAssetRef",
    "MediaProfile",
    "MetricAggregation",
    "MetricDescriptor",
    "MetricDimension",
    "MetricDirection",
    "MetricName",
    "MetricObservation",
    "MetricProvenance",
    "MetricUnit",
    "MetricVector",
    "ModelIdentity",
    "Observation",
    "ObservationId",
    "ObservationKind",
    "ObservationMetadata",
    "ObservationMetadataInterpretation",
    "Point3DEstimate",
    "ProducerRef",
    "ProvenanceClass",
    "QualityDecision",
    "QualityEvaluation",
    "QualityEvaluationReason",
    "QualityEvaluationReasonKind",
    "QualityMode",
    "QualityPolicy",
    "QualityPolicyFailureRule",
    "QualityPolicyId",
    "QualityPolicyMetricRule",
    "QualityPolicyRevision",
    "RawMetadataEntry",
    "ReconstructionRun",
    "ReconstructionRunId",
    "SceneProject",
    "SceneProjectId",
    "Sha256Digest",
    "SourceId",
    "SourceRef",
    "SparseReconstructionEstimate",
    "SparseReconstructionEstimateId",
    "SpatialFragment",
    "SpatialFragmentId",
    "VideoFrameObservation",
    "VideoObservation",
    "build_decoded_image_level_descriptors",
    "canonical_artifact_key_bytes",
    "derive_artifact_key",
    "evaluate_quality_policy",
    "plan_artifact_invalidation",
]
