"""Core solver-independent domain models."""

from wre.domain.adapter_capabilities import AdapterCapabilityDescriptor, AdapterCapabilityName
from wre.domain.appearance import (
    APPEARANCE_MODEL_ARTIFACT_KIND,
    AppearanceModel,
    AppearanceRepresentationName,
)
from wre.domain.artifact_graph import ArtifactDependencyEdge, ArtifactDependencyGraph
from wre.domain.artifact_invalidation import (
    ArtifactInvalidationPlan,
    plan_artifact_invalidation,
)
from wre.domain.artifact_keys import (
    ARTIFACT_KEY_SCHEMA_VERSION,
    ArtifactInputFingerprint,
    ArtifactKey,
    ArtifactKeyMaterial,
    canonical_artifact_key_bytes,
    derive_artifact_key,
)
from wre.domain.artifact_materialization import (
    ArtifactMaterializationEntry,
    ArtifactMaterializationMetadata,
    ArtifactMaterializationVerification,
    ArtifactMaterializationVerificationStatus,
)
from wre.domain.artifact_metadata import ArtifactMetadata
from wre.domain.artifacts import ArtifactId, ArtifactKind, ArtifactRef
from wre.domain.benchmarks import (
    BenchmarkFixtureId,
    BenchmarkFixtureIdentity,
    BenchmarkRecord,
    BenchmarkRecordId,
)
from wre.domain.camera_solutions import (
    CameraProjectionModelName,
    CameraSolution,
    CameraSolutionId,
)
from wre.domain.cameras import (
    Camera,
    CameraId,
    ImageDimensions,
    ObservationMetadata,
    RawMetadataEntry,
)
from wre.domain.color_conventions import (
    LINEAR_SRGB_F64,
    REFERENCE_COLOR_BACKEND,
    ColorConvention,
    ColorConversionAssessment,
    ColorConversionPlan,
    ColorConversionRequest,
    ColorConversionStatus,
    ColorConversionStep,
    ColorPrimaries,
    ColorReferenceBackend,
    ColorSampleStorage,
    ColorTransfer,
    DecodedPixelColorEncoding,
    assess_color_conversion,
)
from wre.domain.decoded_images import (
    DECODED_IMAGE_PYRAMID_KIND,
    DecodedImageLevelDescriptor,
    DecodedImageOrientationPolicy,
    DecodedImagePixelLayout,
    DecodedImagePyramidManifest,
    DecodedImagePyramidSpec,
    build_decoded_image_level_descriptors,
)
from wre.domain.depth_fields import DepthField, DepthFieldId, DepthValueConventionName
from wre.domain.estimated_geometry import (
    CameraCalibrationEstimate,
    CameraCalibrationEstimateId,
    CameraPoseEstimate,
    EstimatedPoint3DId,
    EstimatedTrackElement,
    LocalScaleStatus,
    Point3DEstimate,
    SparseReconstructionEstimate,
    SparseReconstructionEstimateId,
)
from wre.domain.failures import FailureCategory
from wre.domain.fragments import LocalFrameId, SpatialFragment, SpatialFragmentId
from wre.domain.frame_selection import (
    FrameSelectionPolicy,
    FrameSelectionPolicyId,
    FrameSelectionPolicyRevision,
)
from wre.domain.geometry_solutions import (
    GeometryScaleStatus,
    GeometrySolution,
    GeometrySolutionId,
)
from wre.domain.hardware_identity import HardwareRuntimeIdentity
from wre.domain.media_profiles import MediaProfile
from wre.domain.metadata import (
    CaptureTimeInterpretation,
    CaptureTimeInterpretationStatus,
    GpsInterpretationStatus,
    GpsMetadataInterpretation,
    ObservationMetadataInterpretation,
)
from wre.domain.metrics import (
    MetricAggregation,
    MetricDescriptor,
    MetricDimension,
    MetricDirection,
    MetricName,
    MetricObservation,
    MetricProvenance,
    MetricUnit,
    MetricVector,
)
from wre.domain.observations import (
    ImageObservation,
    MediaAssetRef,
    Observation,
    ObservationId,
    ObservationKind,
    Sha256Digest,
    SourceId,
    SourceRef,
    VideoFrameObservation,
    VideoObservation,
)
from wre.domain.pair_candidates import (
    PairCandidate,
    PairCandidateSource,
    PairCandidateSourceId,
    merge_pair_candidates,
)
from wre.domain.photometric_normalization import (
    REFERENCE_PHOTOMETRIC_NORMALIZATION_BACKEND,
    PhotometricNormalizationAssessment,
    PhotometricNormalizationBackend,
    PhotometricNormalizationFactors,
    PhotometricNormalizationPlan,
    PhotometricNormalizationRequest,
    PhotometricNormalizationStatus,
    PhotometricNormalizationStep,
    assess_photometric_normalization,
)
from wre.domain.photometric_validity import (
    PhotometricChannelMask,
    PhotometricCompatibilityAssessment,
    PhotometricCompatibilityInput,
    PhotometricCompatibilityStatus,
    PhotometricMaskKind,
    PhotometricValidityMasks,
    PhotometricValidityRequest,
    assess_photometric_compatibility,
)
from wre.domain.point_maps import PointMap, PointMapId
from wre.domain.producer_identity import (
    ArtifactProducerIdentity,
    CheckpointIdentity,
    ConfigurationIdentity,
    ModelIdentity,
)
from wre.domain.projects import SceneProject, SceneProjectId
from wre.domain.provenance import ProvenanceClass
from wre.domain.quality import QualityDecision, QualityMode
from wre.domain.quality_policy import (
    QualityEvaluation,
    QualityEvaluationReason,
    QualityEvaluationReasonKind,
    QualityPolicy,
    QualityPolicyFailureRule,
    QualityPolicyId,
    QualityPolicyMetricRule,
    QualityPolicyRevision,
    evaluate_quality_policy,
)
from wre.domain.runs import (
    DerivedArtifactProvenance,
    ProducerRef,
    ReconstructionRun,
    ReconstructionRunId,
)
from wre.domain.scene_clusters import (
    SceneCluster,
    SceneClusterId,
    SceneRelationDisposition,
    SceneRelationHypothesis,
)
from wre.domain.source_photometry import (
    SourceColorMetadata,
    SourceExposureMetadata,
    SourcePhotometryInterpretationStatus,
    SourcePhotometryMetadata,
    SourceWhiteBalanceMetadata,
)
from wre.domain.surface_support import (
    SURFACE_SUPPORT_MAP_ARTIFACT_KIND,
    SurfaceRegionSupportStatus,
    SurfaceSupportMap,
    SurfaceSupportRegion,
)
from wre.domain.surfaces import (
    SURFACE_MODEL_ARTIFACT_KIND,
    SurfaceIntendedUse,
    SurfaceModel,
    SurfaceRepresentationName,
)
from wre.domain.temporal_groups import (
    SyncHypothesis,
    SyncHypothesisDisposition,
    TemporalGroup,
    TemporalGroupId,
)

__all__ = [
    "APPEARANCE_MODEL_ARTIFACT_KIND",
    "ARTIFACT_KEY_SCHEMA_VERSION",
    "DECODED_IMAGE_PYRAMID_KIND",
    "LINEAR_SRGB_F64",
    "REFERENCE_COLOR_BACKEND",
    "REFERENCE_PHOTOMETRIC_NORMALIZATION_BACKEND",
    "SURFACE_MODEL_ARTIFACT_KIND",
    "SURFACE_SUPPORT_MAP_ARTIFACT_KIND",
    "AdapterCapabilityDescriptor",
    "AdapterCapabilityName",
    "ArtifactDependencyEdge",
    "ArtifactDependencyGraph",
    "ArtifactId",
    "ArtifactInputFingerprint",
    "ArtifactInvalidationPlan",
    "ArtifactKey",
    "ArtifactKeyMaterial",
    "ArtifactKind",
    "ArtifactMaterializationEntry",
    "ArtifactMaterializationMetadata",
    "ArtifactMaterializationVerification",
    "ArtifactMaterializationVerificationStatus",
    "ArtifactMetadata",
    "ArtifactProducerIdentity",
    "ArtifactRef",
    "AppearanceModel",
    "AppearanceRepresentationName",
    "BenchmarkFixtureId",
    "BenchmarkFixtureIdentity",
    "BenchmarkRecord",
    "BenchmarkRecordId",
    "Camera",
    "CameraCalibrationEstimate",
    "CameraCalibrationEstimateId",
    "CameraId",
    "CameraPoseEstimate",
    "CameraProjectionModelName",
    "CameraSolution",
    "CameraSolutionId",
    "CaptureTimeInterpretation",
    "CaptureTimeInterpretationStatus",
    "CheckpointIdentity",
    "ColorConvention",
    "ColorConversionAssessment",
    "ColorConversionPlan",
    "ColorConversionRequest",
    "ColorConversionStatus",
    "ColorConversionStep",
    "ColorPrimaries",
    "ColorReferenceBackend",
    "ColorSampleStorage",
    "ColorTransfer",
    "ConfigurationIdentity",
    "DecodedImageLevelDescriptor",
    "DecodedImageOrientationPolicy",
    "DecodedImagePixelLayout",
    "DecodedImagePyramidManifest",
    "DecodedImagePyramidSpec",
    "DecodedPixelColorEncoding",
    "DepthField",
    "DepthFieldId",
    "DepthValueConventionName",
    "DerivedArtifactProvenance",
    "EstimatedPoint3DId",
    "EstimatedTrackElement",
    "FailureCategory",
    "FrameSelectionPolicy",
    "FrameSelectionPolicyId",
    "FrameSelectionPolicyRevision",
    "GeometryScaleStatus",
    "GeometrySolution",
    "GeometrySolutionId",
    "GpsInterpretationStatus",
    "GpsMetadataInterpretation",
    "HardwareRuntimeIdentity",
    "ImageDimensions",
    "ImageObservation",
    "LocalFrameId",
    "LocalScaleStatus",
    "MediaAssetRef",
    "MediaProfile",
    "MetricAggregation",
    "MetricDescriptor",
    "MetricDimension",
    "MetricDirection",
    "MetricName",
    "MetricObservation",
    "MetricProvenance",
    "MetricUnit",
    "MetricVector",
    "ModelIdentity",
    "Observation",
    "ObservationId",
    "ObservationKind",
    "ObservationMetadata",
    "ObservationMetadataInterpretation",
    "PairCandidate",
    "PairCandidateSource",
    "PairCandidateSourceId",
    "PhotometricChannelMask",
    "PhotometricCompatibilityAssessment",
    "PhotometricCompatibilityInput",
    "PhotometricCompatibilityStatus",
    "PhotometricMaskKind",
    "PhotometricNormalizationAssessment",
    "PhotometricNormalizationBackend",
    "PhotometricNormalizationFactors",
    "PhotometricNormalizationPlan",
    "PhotometricNormalizationRequest",
    "PhotometricNormalizationStatus",
    "PhotometricNormalizationStep",
    "PhotometricValidityMasks",
    "PhotometricValidityRequest",
    "Point3DEstimate",
    "PointMap",
    "PointMapId",
    "ProducerRef",
    "ProvenanceClass",
    "QualityDecision",
    "QualityEvaluation",
    "QualityEvaluationReason",
    "QualityEvaluationReasonKind",
    "QualityMode",
    "QualityPolicy",
    "QualityPolicyFailureRule",
    "QualityPolicyId",
    "QualityPolicyMetricRule",
    "QualityPolicyRevision",
    "RawMetadataEntry",
    "ReconstructionRun",
    "ReconstructionRunId",
    "SceneCluster",
    "SceneClusterId",
    "SceneProject",
    "SceneProjectId",
    "SceneRelationDisposition",
    "SceneRelationHypothesis",
    "Sha256Digest",
    "SourceColorMetadata",
    "SourceExposureMetadata",
    "SourceId",
    "SourcePhotometryInterpretationStatus",
    "SourcePhotometryMetadata",
    "SourceRef",
    "SourceWhiteBalanceMetadata",
    "SparseReconstructionEstimate",
    "SparseReconstructionEstimateId",
    "SpatialFragment",
    "SpatialFragmentId",
    "SurfaceIntendedUse",
    "SurfaceModel",
    "SurfaceRegionSupportStatus",
    "SurfaceRepresentationName",
    "SurfaceSupportMap",
    "SurfaceSupportRegion",
    "SyncHypothesis",
    "SyncHypothesisDisposition",
    "TemporalGroup",
    "TemporalGroupId",
    "VideoFrameObservation",
    "VideoObservation",
    "assess_color_conversion",
    "assess_photometric_compatibility",
    "assess_photometric_normalization",
    "build_decoded_image_level_descriptors",
    "canonical_artifact_key_bytes",
    "derive_artifact_key",
    "evaluate_quality_policy",
    "merge_pair_candidates",
    "plan_artifact_invalidation",
]
