"""External reconstruction-engine adapters and environment contracts."""

from wre.reconstruction.colmap_environment import (
    SUPPORTED_COLMAP_VERSION,
    SUPPORTED_PYCOLMAP_VERSION,
    ColmapEnvironmentError,
    ColmapEnvironmentIdentity,
    inspect_colmap_environment,
)
from wre.reconstruction.colmap_features import (
    ColmapFeatureExtractionConfig,
    ColmapFeatureExtractionError,
    ColmapFeatureExtractionRequest,
    ColmapFeatureExtractionResult,
    ColmapFeatureInput,
    ColmapImageFeatureSummary,
    extract_colmap_features,
)
from wre.reconstruction.colmap_import import (
    COLMAP_IMPORTER_VERSION,
    ColmapReconstructionImportConfig,
    ColmapReconstructionImportError,
    ColmapReconstructionImportRequest,
    ColmapReconstructionImportResult,
    ImportedColmapSparseModel,
    import_colmap_reconstruction,
)
from wre.reconstruction.colmap_matching import (
    ColmapPairMatchingConfig,
    ColmapPairMatchingError,
    ColmapPairMatchingRequest,
    ColmapPairMatchingResult,
    ColmapPairMatchSummary,
    match_colmap_pairs,
)
from wre.reconstruction.colmap_reconstruction import (
    ColmapIncrementalReconstructionConfig,
    ColmapIncrementalReconstructionError,
    ColmapIncrementalReconstructionRequest,
    ColmapIncrementalReconstructionResult,
    ColmapModelFileArtifact,
    ColmapReconstructionInput,
    ColmapSparseModelArtifact,
    reconstruct_colmap_incrementally,
)
from wre.reconstruction.colmap_verification import (
    ColmapGeometricVerificationConfig,
    ColmapGeometricVerificationError,
    ColmapGeometricVerificationRequest,
    ColmapGeometricVerificationResult,
    ColmapPairGeometryEvidence,
    verify_colmap_geometry,
)
from wre.reconstruction.legacy_geometry_conversion import (
    LegacySparseGeometryConversionResult,
    convert_sparse_reconstruction_estimate,
)

__all__ = [
    "COLMAP_IMPORTER_VERSION",
    "SUPPORTED_COLMAP_VERSION",
    "SUPPORTED_PYCOLMAP_VERSION",
    "ColmapEnvironmentError",
    "ColmapEnvironmentIdentity",
    "ColmapFeatureExtractionConfig",
    "ColmapFeatureExtractionError",
    "ColmapFeatureExtractionRequest",
    "ColmapFeatureExtractionResult",
    "ColmapFeatureInput",
    "ColmapGeometricVerificationConfig",
    "ColmapGeometricVerificationError",
    "ColmapGeometricVerificationRequest",
    "ColmapGeometricVerificationResult",
    "ColmapImageFeatureSummary",
    "ColmapIncrementalReconstructionConfig",
    "ColmapIncrementalReconstructionError",
    "ColmapIncrementalReconstructionRequest",
    "ColmapIncrementalReconstructionResult",
    "ColmapModelFileArtifact",
    "ColmapPairGeometryEvidence",
    "ColmapPairMatchSummary",
    "ColmapPairMatchingConfig",
    "ColmapPairMatchingError",
    "ColmapPairMatchingRequest",
    "ColmapPairMatchingResult",
    "ColmapReconstructionImportConfig",
    "ColmapReconstructionImportError",
    "ColmapReconstructionImportRequest",
    "ColmapReconstructionImportResult",
    "ColmapReconstructionInput",
    "ColmapSparseModelArtifact",
    "ImportedColmapSparseModel",
    "LegacySparseGeometryConversionResult",
    "convert_sparse_reconstruction_estimate",
    "extract_colmap_features",
    "import_colmap_reconstruction",
    "inspect_colmap_environment",
    "match_colmap_pairs",
    "reconstruct_colmap_incrementally",
    "verify_colmap_geometry",
]
