"""Deterministic candidate-retrieval policies."""

from wre.retrieval.gps import (
    COLMAP_SPATIAL_REFERENCE_VERSION,
    GPS_DISTANCE_MODEL,
    GPS_MAP_DATUM_POLICY,
    GPS_PAIRING_IMPLEMENTATION,
    GPS_PAIRING_VERSION,
    GpsPairCandidate,
    GpsPairingConfig,
    GpsPairingEligibility,
    GpsPairingEligibilityStatus,
    GpsPairingRequest,
    GpsPairingResult,
    generate_gps_candidates,
)
from wre.retrieval.gps_adapter import (
    GPS_PAIR_CANDIDATE_SOURCE_ID,
    GpsPairCandidateAdapterInput,
    adapt_gps_pairing_result,
)
from wre.retrieval.sequential import (
    COLMAP_SEQUENTIAL_REFERENCE_VERSION,
    SEQUENTIAL_PAIRING_IMPLEMENTATION,
    SEQUENTIAL_PAIRING_VERSION,
    SequentialPairCandidate,
    SequentialPairingConfig,
    SequentialPairingRequest,
    SequentialPairingResult,
    generate_sequential_candidates,
)
from wre.retrieval.sequential_adapter import (
    SEQUENTIAL_PAIR_CANDIDATE_SOURCE_ID,
    SequentialPairCandidateAdapterInput,
    adapt_sequential_pairing_result,
)
from wre.retrieval.vocab_tree import (
    COLMAP_VOCAB_TREE_RETRIEVAL_IMPLEMENTATION,
    COLMAP_VOCAB_TREE_RETRIEVAL_VERSION,
    VOCAB_TREE_PAIR_CANDIDATE_SOURCE_ID,
    ColmapVocabTreePair,
    ColmapVocabTreePairCandidateAdapterInput,
    ColmapVocabTreeRetrievalError,
    ColmapVocabTreeRetrievalRequest,
    ColmapVocabTreeRetrievalResult,
    VocabTreeRetrievalConfig,
    adapt_colmap_vocab_tree_retrieval_result,
    retrieve_colmap_vocab_tree_pairs,
)

__all__ = [
    "adapt_colmap_vocab_tree_retrieval_result",
    "adapt_gps_pairing_result",
    "adapt_sequential_pairing_result",
    "COLMAP_SEQUENTIAL_REFERENCE_VERSION",
    "COLMAP_SPATIAL_REFERENCE_VERSION",
    "COLMAP_VOCAB_TREE_RETRIEVAL_IMPLEMENTATION",
    "COLMAP_VOCAB_TREE_RETRIEVAL_VERSION",
    "ColmapVocabTreePair",
    "ColmapVocabTreePairCandidateAdapterInput",
    "ColmapVocabTreeRetrievalError",
    "ColmapVocabTreeRetrievalRequest",
    "ColmapVocabTreeRetrievalResult",
    "generate_gps_candidates",
    "generate_sequential_candidates",
    "GPS_DISTANCE_MODEL",
    "GPS_MAP_DATUM_POLICY",
    "GPS_PAIR_CANDIDATE_SOURCE_ID",
    "GPS_PAIRING_IMPLEMENTATION",
    "GPS_PAIRING_VERSION",
    "GpsPairCandidate",
    "GpsPairCandidateAdapterInput",
    "GpsPairingConfig",
    "GpsPairingEligibility",
    "GpsPairingEligibilityStatus",
    "GpsPairingRequest",
    "GpsPairingResult",
    "retrieve_colmap_vocab_tree_pairs",
    "SEQUENTIAL_PAIR_CANDIDATE_SOURCE_ID",
    "SEQUENTIAL_PAIRING_IMPLEMENTATION",
    "SEQUENTIAL_PAIRING_VERSION",
    "SequentialPairCandidate",
    "SequentialPairCandidateAdapterInput",
    "SequentialPairingConfig",
    "SequentialPairingRequest",
    "SequentialPairingResult",
    "VOCAB_TREE_PAIR_CANDIDATE_SOURCE_ID",
    "VocabTreeRetrievalConfig",
]
