"""Media-ingestion services built on the solver-independent domain contracts."""

from wre.ingestion.exif import (
    EXIF_NAMESPACE,
    ExifMetadataIngestor,
    ExifMetadataIngestRequest,
    ObservationMetadataSink,
    extract_exif_entries,
)
from wre.ingestion.hashing import (
    DEFAULT_HASH_CHUNK_SIZE,
    DuplicateObservationLookup,
    FileContentHash,
    LocalImageIngestor,
    LocalImageIngestRequest,
    LocalImageIngestResult,
    LocalVideoIngestor,
    LocalVideoIngestRequest,
    LocalVideoIngestResult,
    hash_file_content,
)
from wre.ingestion.images import ImageIngestor, ImageIngestRequest, ObservationSink
from wre.ingestion.keyframes import (
    FFmpegExecutionError,
    FFmpegToolchain,
    FFmpegToolchainIdentity,
    KeyframeExtractionRequest,
    KeyframeExtractionResult,
    KeyframeSelectionPolicy,
    LocalKeyframeExtractor,
    ProbedVideoFrame,
    inspect_toolchain,
    parse_ffprobe_frames,
    probe_video_frames,
    select_keyframes,
)
from wre.ingestion.metadata_interpretation import (
    MetadataInterpretationSink,
    MetadataInterpreter,
    interpret_observation_metadata,
)
from wre.ingestion.videos import VideoIngestor, VideoIngestRequest

__all__ = [
    "DEFAULT_HASH_CHUNK_SIZE",
    "EXIF_NAMESPACE",
    "DuplicateObservationLookup",
    "ExifMetadataIngestRequest",
    "ExifMetadataIngestor",
    "FFmpegExecutionError",
    "FFmpegToolchain",
    "FFmpegToolchainIdentity",
    "FileContentHash",
    "ImageIngestRequest",
    "ImageIngestor",
    "KeyframeExtractionRequest",
    "KeyframeExtractionResult",
    "KeyframeSelectionPolicy",
    "LocalImageIngestRequest",
    "LocalImageIngestResult",
    "LocalImageIngestor",
    "LocalKeyframeExtractor",
    "LocalVideoIngestRequest",
    "LocalVideoIngestResult",
    "LocalVideoIngestor",
    "MetadataInterpretationSink",
    "MetadataInterpreter",
    "ObservationMetadataSink",
    "ObservationSink",
    "ProbedVideoFrame",
    "VideoIngestRequest",
    "VideoIngestor",
    "extract_exif_entries",
    "hash_file_content",
    "inspect_toolchain",
    "interpret_observation_metadata",
    "parse_ffprobe_frames",
    "probe_video_frames",
    "select_keyframes",
]
